### ISSUE TITLE
allow maintainers to apply for badge

### ISSUE THREAD

**Issue by kaxada** [badging/BadgingAPI#10]
This issue came up from [this slack conversation](https://chaoss-workspace.slack.com/archives/C012A4L7M8V/p1702931935054529)

**Comment by dm-murphy** [comment]
@kaxada I think we can close this issue for now since the decision was made to only have project owners apply for badges. Site has been updated now accordingly to indicate ownership requirement.

**Comment by kaxada** [comment]
yeah sure. Thanks @dm-murphy
