### ISSUE TITLE
code cleaning

### ISSUE THREAD

**Issue by kaxada** [badging/BadgingAPI#22]
This issue is intended to clean up some aspects of the code. This issue focuses on;

- removing all the redundant code that was commented out

- commenting on the necessary comments

- change the casing to match the following rules:
1. Variables and functions: CamelCase
2. Classes and constructors: PascalCase
3. Filenames, constants, and environment variables: Snake_case
4. HTML attributes and CSS class names: Kebab-case

While you are doing so, Please make sure your code never breaks in any way. Be sure to always be running the dev server

**Comment by DesmondSanctity** [comment]
@kaxada I'll work on this

**Comment by kaxada** [comment]
@DesmondSanctity I'll assign it to you.

Sending up the local environment maybe challenging. (I hope it's not). Please let know when you get an issues.

And I hope it takes a week otherwise we may assume that you're not working on it and reassign it someone else

**Comment by DesmondSanctity** [comment]
> @DesmondSanctity I'll assign it to you.
> 
> Sending up the local environment maybe challenging. (I hope it's not). Please let know when you get an issues.
> 
> And I hope it takes a week otherwise we may assume that you're not working on it and reassign it someone else

Noted!!!

**Comment by jude-san** [comment]
Hi @kaxada looks like I am going to miss all the fun stuffs.

**Comment by kaxada** [comment]
@jude-san please look through more open issues. you can also check out https://github.com/badging/Badging/issues
