### ISSUE TITLE
Update `contributing.md`

### ISSUE THREAD

**Issue by kaxada** [badging/BadgingAPI#28]
Issue #22 created a standard for naming files and folders. The goal of this issue is to update the [CONTRIBUTING.md](https://github.com/badging/BadgingAPI/blob/main/CONTRIBUTING.md) to reflect the standard that is in the description of issue #22

**Comment by aaron-ross-sanchez** [comment]
I can work on this!

**Comment by kaxada** [comment]
@aaron-ross-sanchez there you go!

**Comment by aaron-ross-sanchez** [comment]
Ready to be checked! This is my first contribution to an open source project, so I do apologize if there is any trouble with the pull request, but I would love to learn how to do it more efficiently if needed! Thank you for letting me contribute, please let me know if anything needs to be changed on my part!

**Comment by kaxada** [comment]
This was well done @aaron-ross-sanchez
