### ISSUE TITLE
[FEATURE]: Endpoint for submitting "In-Person Events" and "Virtual Events" Application forms 

### ISSUE THREAD

**Issue by adeyinkaoresanya** [badging/BadgingAPI#48]
**Current Situation**

The application forms for in-person and virtual event badging are being developed for integration into the badging website. However, there is no backend endpoint to handle the submission of these forms, which is essential for processing user applications.

**Proposed Solution**
Develop an API endpoint that handles the submission of the in-person and virtual event badging application forms. This endpoint will collect the form data, convert to a markdown format and create an issue for the applicant on the [events-diversity-and-inclusion repo](https://github.com/badging/event-diversity-and-inclusion/issues) using the user's GitHub authentication. This is related to this [issue](https://github.com/badging/badging/issues/82)

**Benefit**
Seamless Data Handling: Allows the badging application to submit form data directly, ensuring no disruption in the user journey after form submission.

**Comment by adeyinkaoresanya** [comment]
@DesmondSanctity pinging you on this

**Comment by DesmondSanctity** [comment]
Noted @adeyinkaoresanya .
